name: CodSpeed

env:
  DEBUG: napi:*
  APP_NAME: image

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - name: Setup nasm
        uses: ilammy/setup-nasm@v1

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: codspeed-x86_64-unknown-linux-gnu-cargo-cache

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Build native binding
        run: yarn workspace @napi-rs/image build
        env:
          CC: clang
          CXX: clang++

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: yarn vitest bench --run
